"""create initial tables

Revision ID: d915563fcf41
Revises: 
Create Date: 2026-05-12 19:44:42.416427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd915563fcf41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tribunals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_table('lawsuits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tribunal_id', sa.Integer(), nullable=False),
    sa.Column('class', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('court', sa.String(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('control', sa.String(), nullable=True),
    sa.Column('action_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('consulta_processual', 'datajud', 'esaj', name='sourcetype'), nullable=True),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tribunal_id'], ['tribunals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hearings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawsuit_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lawsuit_id'], ['lawsuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawsuit_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lawsuit_id'], ['lawsuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawsuit_id', sa.String(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lawsuit_id'], ['lawsuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawsuit_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('lawyer_name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.Enum('author', 'defendant', 'third_party', name='participanttype'), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['lawsuit_id'], ['lawsuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawsuit_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lawsuit_id'], ['lawsuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawsuit_id', sa.String(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lawsuit_id'], ['lawsuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('petitions')
    op.drop_table('participants')
    op.drop_table('movements')
    op.drop_table('incidents')
    op.drop_table('hearings')
    op.drop_table('lawsuits')
    op.drop_table('tribunals')
    # ### end Alembic commands ###
